services:
  edge-sensor:
    build: .
    restart: unless-stopped
    privileged: true
    env_file: .env
    volumes:
      - ./data:/data
      - ./src:/app/src
      - ./tests:/app/tests
      - /dev:/dev
      - /run/udev:/run/udev
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/i2c-2:/dev/i2c-2
      - /dev/spidev0.0:/dev/spidev0.0
#      - /dev/ttyUSB0:/dev/ttyUSB0
